import fs from "node:fs";
import path from "node:path";
import type { GraphLink, GraphNode } from "../../src/graph/graphTypes";

type EmitGraphDataOptions = {
  root: string;
  outPath: string;
  bodiesPath: string;
  codeBodiesPath: string;
  bodies: Record<string, string>;
  codeBodies: Record<string, string>;
  nodes: GraphNode[];
  graphLinks: GraphLink[];
};

export function emitGraphData({
  root,
  outPath,
  bodiesPath,
  codeBodiesPath,
  bodies,
  codeBodies,
  nodes,
  graphLinks,
}: EmitGraphDataOptions): void {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(
    outPath,
    [
      "// Generated by scripts/build-obsidian-graph.ts. Do not edit by hand.",
      "",
      `import type { GraphData } from ${JSON.stringify(typeImport(root, outPath))};`,
      "",
      "export const graphData = {",
      `  nodes: ${JSON.stringify(nodes, null, 2)},`,
      `  links: ${JSON.stringify(graphLinks)},`,
      "} as const satisfies GraphData;",
      "",
    ].join("\n"),
  );
  fs.writeFileSync(
    bodiesPath,
    [
      "// Generated by scripts/build-obsidian-graph.ts. Do not edit by hand.",
      "",
      "export const graphBodies = ",
      `${JSON.stringify(bodies, null, 2)} as const;`,
      "",
    ].join("\n"),
  );
  fs.writeFileSync(
    codeBodiesPath,
    [
      "// Generated by scripts/build-obsidian-graph.ts. Do not edit by hand.",
      "",
      "export const graphCodeBodies = ",
      `${JSON.stringify(codeBodies, null, 2)} as const;`,
      "",
    ].join("\n"),
  );
  console.log(
    `Wrote ${path.relative(root, outPath)}: ${nodes.length} notes, ${graphLinks.length} links`,
  );
}

function typeImport(root: string, outPath: string): string {
  const from = path.dirname(outPath);
  const to = path.join(root, "src/graph/graphTypes");
  const specifier = path.relative(from, to).replaceAll(path.sep, "/");
  return specifier.startsWith(".") ? specifier : `./${specifier}`;
}
